### ISSUE TITLE
Keras Applications progress tracker

### ISSUE THREAD

**Issue by fchollet** [keras-team/keras-core#191]
- [x] VGG*: @fchollet 
- [x] Xception: @fchollet
- [x] ResNet*: @AakashKumarNain 
- [x] ResNet*V2: @AakashKumarNain 
- [x] InceptionV3: @fchollet 
- [x] InceptionResNetV2: @fchollet 
- [x] MobileNet: @fchollet 
- [x] MobileNetV2: @fchollet 
- [x] DenseNet*: @fchollet
- [x] NASNet*: @fchollet 
- [x] EfficientNet*: @fchollet 
- [x] ConvNeXt*: @fchollet

**Comment by IMvision12** [comment]
@fchollet what about resnetrs and regnet models?
