### ISSUE TITLE
Example `nlp/lstm_seq2seq.py` doesn't train with JAX backend

### ISSUE THREAD

**Issue by fchollet** [keras-team/keras-core#322]
The model trains fine with TF. With JAX, the code runs but trains rather poorly. Need to find out root cause.

In addition, in this example, a model trained with TF cannot be reloaded with JAX.

**Comment by shivance** [comment]
Hi @fchollet, can I contribute here ?

**Comment by ariG23498** [comment]
While working on the code the "tensorflow" backend threw an error.

Here is the Gist to reproduce the error: https://gist.github.com/ariG23498/b8b4c0912a0a19dfe2ef8b29b3160943

**Comment by fchollet** [comment]
The error message tells you that cuDNN can't be compiled to XLA, basically. It's somewhat tricky to solve on our side. Either we disable jit_compile if there's a cuDNN-enabled layer, or we don't use cuDNN if we detect we're tracing for XLA?

**Comment by fchollet** [comment]
To work around this you can just pass `jit_compile=False` to `compileI()`.

**Comment by ariG23498** [comment]
> To work around this you can just pass `jit_compile=False` to `compile()` when using TF.

Right! Now it trains using tf backend.

The same issue persists when loading the saved model it seems. Do I also need to pass `compile=False` when loading the saved model (when using TensorFlow as backend)?

**Comment by fchollet** [comment]
> Do I also need to pass compile=False when loading the saved model (when using TensorFlow as backend)?

You can just set `jit_compile = False` on the model I think.

**Comment by fchollet** [comment]
@ariG23498 I have fixed it in this commit, please check that it works for you. https://github.com/keras-team/keras-core/commit/c9bce12d591c34f752c57800b921982c59320ea4

**Comment by qlzh727** [comment]
ok, I was able to verify my fix in https://github.com/keras-team/keras-core/pull/888 to fix this issue. 

See https://colab.corp.google.com/drive/1z_QDD0uX9ApLJdFTxhHYxJNejUdgowkG#scrollTo=kxjMd749C1nA. Will send a PR very soon.
