### ISSUE TITLE
Add FFT Op

### ISSUE THREAD

**Issue by abheesht17** [keras-team/keras-core#429]
1D FFT:
https://www.tensorflow.org/api_docs/python/tf/signal/fft
https://pytorch.org/docs/stable/generated/torch.fft.fft.html#torch.fft.fft
https://jax.readthedocs.io/en/latest/_autosummary/jax.numpy.fft.fft.html

We can similarly add 2D FFT ops. These ops will be useful for porting FNet (present in KerasNLP).

@fchollet - I wanted to know where these ops should reside. Should they be inside https://github.com/keras-team/keras-core/blob/main/keras_core/ops/numpy.py? Or should we create a separate file for all fft ops?

CC: @mattdangerw

**Comment by fchollet** [comment]
Matt's solution sounds good, let's go with the tuple approach.
