### ISSUE TITLE
Getting started with Keras Core didn't work successfully on Mac M2

### ISSUE THREAD

**Issue by ramkumarkoppu** [keras-team/keras-core#446]
Tried example code provided in the https://keras.io/keras_core/guides/getting_started_with_keras_core/ on Apple Silicon Mac (keras_core page says it has support for Mac as well), and model.summary() throws following error:

`---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[4], line 1
----> 1 model.summary()

File ~/tf-keras-core/lib/python3.11/site-packages/keras_core/src/utils/traceback_utils.py:124, in filter_traceback.<locals>.error_handler(*args, **kwargs)
    121     filtered_tb = _process_traceback_frames(e.__traceback__)
    122     # To get the full stack trace, call:
    123     # `keras_core.config.disable_traceback_filtering()`
--> 124     raise e.with_traceback(filtered_tb) from None
    125 finally:
    126     del filtered_tb

File ~/tf-keras-core/lib/python3.11/site-packages/keras_core/src/utils/summary_utils.py:212, in print_summary(model, line_length, positions, print_fn, expand_nested, show_trainable, layer_range)
    210 # Right align parameter counts.
    211 for i, name in enumerate(header):
--> 212     column = rich.table.Column(
    213         name,
    214         justify=alignment[i],
    215         width=column_widths[i],
    216     )
    217     columns.append(column)
    219 table = rich.table.Table(*columns, width=line_length, show_lines=True)

AttributeError: module 'rich' has no attribute 'table'`

Jupyter notebook of the entire code is here: https://drive.google.com/file/d/16QyRaue_M9CgpFiIcfd0M04gfYHOArjm/view?usp=share_link

**Comment by fchollet** [comment]
It sounds like you just need to update your `rich` version?

**Comment by ramkumarkoppu** [comment]
installed rich version is 13.4.2, same as what is latest in https://pypi.org/project/rich/
should it be specific older version of rich needed on Mac?

**Comment by fchollet** [comment]
I run Keras Core on a M2 Mac and never had this issue. But someone else reported the same issue today. I assume it's some kind of environment issue. We issued a fix, so you can just pull the latest code from GitHub and install it via the `python pip_build.py --install` script.

**Comment by ramkumarkoppu** [comment]
Tried python pip_build.py --install from latest repo and ran the same getting started guide with both "torch" and "tensor flow" backends, in both the runs, it fails with the same reason:
`---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[3], line 14
      2 num_classes = 10
      3 input_shape = (28, 28, 1)
      5 model = keras.Sequential(
      6     [
      7         keras.layers.Input(shape=input_shape),
      8         keras.layers.Conv2D(64, kernel_size=(3, 3), activation="relu"),
      9         keras.layers.Conv2D(64, kernel_size=(3, 3), activation="relu"),
     10         keras.layers.MaxPooling2D(pool_size=(2, 2)),
     11         keras.layers.Conv2D(128, kernel_size=(3, 3), activation="relu"),
     12         keras.layers.Conv2D(128, kernel_size=(3, 3), activation="relu"),
     13         keras.layers.GlobalAveragePooling2D(),
---> 14         keras.layers.Dropout(0.5),
     15         keras.layers.Dense(num_classes, activation="softmax"),
     16     ]
     17 )

File ~/keras-core/lib/python3.11/site-packages/keras_core/src/layers/regularization/dropout.py:52, in Dropout.__init__(self, rate, noise_shape, seed, **kwargs)
     50 self.seed = seed
     51 self.noise_shape = noise_shape
---> 52 self.seed_generator = backend.random.SeedGenerator(seed)
     53 self.supports_masking = True
     54 self.built = True

File ~/keras-core/lib/python3.11/site-packages/keras_core/src/random/seed_generator.py:49, in SeedGenerator.__init__(self, seed, **kwargs)
     46     dtype = kwargs.get("dtype", None)
     47     return self.backend.convert_to_tensor([seed, 0], dtype=dtype)
---> 49 self.state = self.backend.Variable(
     50     seed_initializer,
     51     shape=(2,),
     52     dtype="uint32",
     53     trainable=False,
     54     name="seed_generator_state",
     55 )

AttributeError: module 'keras_core.backend' has no attribute 'Variable'
`
