### ISSUE TITLE
Unexpected argument in keras_core/models/functional.py

### ISSUE THREAD

**Issue by Frightera** [keras-team/keras-core#447]
I was surfing through the code and saw:

https://github.com/keras-team/keras-core/blob/f9900337bc85b6bb53c0a8cf584a567607e0b9fa/keras_core/models/functional.py#L149

`Function` class does not accept **kwargs:

https://github.com/keras-team/keras-core/blob/f9900337bc85b6bb53c0a8cf584a567607e0b9fa/keras_core/ops/function.py#L45

If this is a bug, I am happy to fix this with a PR.

**Comment by fchollet** [comment]
It seems fine. If there are kwargs and they aren't accepted, then the user will see an error. If we add kwargs in Function in the future, Functional will automatically support them. And if we didn't pass **kwargs to the parent class we'd have to validate that there are none in Functional, which is unncessary.
