### ISSUE TITLE
model.summary() raises an AttributeError

### ISSUE THREAD

**Issue by ageron** [keras-team/keras-core#448]
When calling `model.summary()`, I get the following error: `AttributeError: module 'rich' has no attribute 'table'` (full stack trace below).

Here's my code:

```python
import keras_core as keras

model = keras.Sequential([keras.layers.Dense(1)])
model.summary()  # ERROR
```

And here's the full stack trace:

<details>

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In [2], line 9
      3 model = keras.Sequential([keras.layers.Dense(1)])
      5 # import rich.table
      6 # import rich.markup
      7 # import rich.console
----> 9 model.summary()

File ~/opt/miniconda3/envs/homl3/lib/python3.10/site-packages/keras_core/src/utils/traceback_utils.py:124, in filter_traceback.<locals>.error_handler(*args, **kwargs)
    121     filtered_tb = _process_traceback_frames(e.__traceback__)
    122     # To get the full stack trace, call:
    123     # `keras_core.config.disable_traceback_filtering()`
--> 124     raise e.with_traceback(filtered_tb) from None
    125 finally:
    126     del filtered_tb

File ~/opt/miniconda3/envs/homl3/lib/python3.10/site-packages/keras_core/src/utils/summary_utils.py:212, in print_summary(model, line_length, positions, print_fn, expand_nested, show_trainable, layer_range)
    210 # Right align parameter counts.
    211 for i, name in enumerate(header):
--> 212     column = rich.table.Column(
    213         name,
    214         justify=alignment[i],
    215         width=column_widths[i],
    216     )
    217     columns.append(column)
    219 table = rich.table.Table(*columns, width=line_length, show_lines=True)

AttributeError: module 'rich' has no attribute 'table'
```

</details>

I can work around the issue by importing `rich.table` before calling `model.summary()`, but then I get another error for `rich.markup`. If I import that I get an error for `rich.console`. And if I import that then `model.summary()` works fine. So a quick workaround is to run:

```python
import keras_core as keras

model = keras.Sequential([keras.layers.Dense(1)])

import rich.table
import rich.markup
import rich.console
model.summary()  # ERROR
```

It looks like Keras-Core's `summary_utils.py` just imports `rich` and then uses `rich.table`, `rich.markup`, and `rich.console`. However, these are not automatically imported when importing `rich`, so it will fail unless these packages have already been imported anywhere else in the code.

I suggest adding `import rich.table`, `import rich.markup`, and `import rich.console` in `summary_utils.py`.

**Comment by mattdangerw** [comment]
Yeah this makes sense. We can just do `from rich import table`, etc, and use `table`, `markup` and `console` directly.

I am curious why this is not happening in all installs though. Can you share your system version, python version, rich version?

**Comment by fchollet** [comment]
I applied your suggested fix -- can you check that the new version on `main` works for you?

**Comment by ageron** [comment]
Thanks @mattdangerw & @fchollet , I just tested your fix François, it works fine now.

<img width="687" alt="image" src="https://github.com/keras-team/keras-core/assets/76661/ce782d5d-8a00-49c5-b6a4-4b81a292a5d2">

**Comment by fchollet** [comment]
Thanks!
