### ISSUE TITLE
[FEATURE] Add scikit-learn backend

### ISSUE THREAD

**Issue by SamuelMarks** [keras-team/keras-core#450]
Looking at my own multi-ML meta-framework [from 3 years ago] I see this support table:

 | Google                                                             | Other vendors                                               |
 | ------------------------------------------------------------------ | ----------------------------------------------------------- |
 | [tensorflow](https://github.com/tensorflow/tensorflow) | [pytorch](https://github.com/pytorch/pytorch)
 | [keras](https://github.com/keras-team/keras)            | [skorch](https://github.com/skorch-dev/skorch)   |
 | [flax](https://github.com/google/flax)              | [scikit-learn](https://github.com/scikit-learn/scikit-learn) |
 | [trax](https://github.com/google/trax)              | [xgboost](https://github.com/dmlc/xgboost) |
 | [jax](https://github.com/google/jax)                | [cntk](https://github.com/microsoft/CNTK)       |

Shorter list from [eagerpy](https://github.com/jonasrauber/eagerpy):
 | Google                                                             | Other vendors                                               |
 | ------------------------------------------------------------------ | ----------------------------------------------------------- |
 | [tensorflow](https://github.com/tensorflow/tensorflow) | [pytorch](https://github.com/pytorch/pytorch)
 | [jax](https://github.com/google/jax) | [numpy](https://github.com/numpy/numpy)

---

I think [scikit-learn](https://github.com/scikit-learn/scikit-learn) is a good target. Probably start with [Scipy](https://github.com/scipy/scipy); either monkey-patching or a straight up fork for transparent replacement of its major dependency.

I understand that NumPy is not technically a backend you're adding support for, but you are building a NumPy compatible library, so it kinda-makes-sense to support the most popular ML framework built atop NumPy.

Happy to contrib myself [if there's interest] when I find some spare hours. Otherwise posting this issue for feedback and to see if there's any collaboration interest.

PS: Might also be worth concentrating on [skorch](https://github.com/skorch-dev/skorch) testing and integration as this uses PyTorch as the backing for a (mostly?) compatible experience to scikit-learn.

**Comment by fchollet** [comment]
Thanks for the suggestion. We are adding a NumPy backend (for inference only).

sklearn is not a differentiable computing runtime, though, it's a high-level ML library. A Keras backend must be a differentiable computing runtime or at least a numerical computing runtime. For instance, it can make sense to add a cuDNN backend or a Mojo backend, but it doesn't make sense for sklearn. The closest computing runtime to sklearn is just numpy.

**Comment by fchollet** [comment]
Also, if you are looking for a way to use Keras models with sklearn, you can try this library https://github.com/adriangb/scikeras
