### ISSUE TITLE
No type hints?

### ISSUE THREAD

**Issue by ksachdeva** [keras-team/keras-core#461]
Thanks for releasing this. I used to work (and love) with Keras, but last year moved to Pytorch (primarily because of the richer ecosystem of modules and research). 

Looking at this repo and other repositories in keras-team, I see that there is no usage of type hints.

Was wondering if this is intentional and perhaps the keras-team does not see value in them. 

Regards
Kapil

**Comment by fchollet** [comment]
Right, this is intentional. We've tried type hints at various occasions in the past and we've found that they cause more trouble than they create value.

**Comment by ksachdeva** [comment]
Thanks for the answer. 

I would have loved to come back and use the abstractions as I still do think Keras layers/abstractions are at the right level in comparison to Pytorch but if a Python library does not use type hints it is a big No for me. 

Thanks for all the great work you and your team have done for the ML community.
