### ISSUE TITLE
[Suggestion] add keras before the `Using XX backend` message

### ISSUE THREAD

**Issue by refraction-ray** [keras-team/keras-core#466]
Since there could be other packages around that print similar message, maybe the following print message is better and more informative for the users to identify and debug.

Instead of `Using XX backend`, print `Keras: Using XX backend` at the beginning. This is also consistent with the default behavior of python logger module: let the users clearly know which package is printing messages.

**Comment by sampathweb** [comment]
Closing this issue based on feedback on the PR.  Agree that we should let User's Logger config do this.
