### ISSUE TITLE
Export `keras.mixed_precision.DTypePolicy` as `keras.mixed_precision.Policy`

### ISSUE THREAD

**Issue by abheesht17** [keras-team/keras-core#468]
In Keras 2.0, we call it `Policy`: https://keras.io/api/mixed_precision/policy/. Was the rename to `DTypePolicy` intentional? We can probably export it as `Policy` and `DTypePolicy` both (if `DTypePolicy` is intentional).

**Comment by fchollet** [comment]
Sure, let's add the alias in the `export` statement for backwards compatibility. Can you open a PR?

**Comment by abheesht17** [comment]
Sure thing!
