### ISSUE TITLE
keras_core tensor assignment error with TensorFlow and JAX backend

### ISSUE THREAD

**Issue by anas-rz** [keras-team/keras-core#476]
While trying to implement a model with keras_core, I faced a problem with  tensor assignment in TensorFlow and JAX:

This is the code I have tried:
```
tensor = keras_core.random.normal((2, 12))
tensor[0, 1] = 2
```
Updating tensor values is tricky in TensorFlow as the most popular (and inefficient) way is to convert it to a `tf.Variable` and then convert it back to tensor.
For JAX, we need to set up values using `set` and `at` methods.

Does `keras_core` has any cross-framework way of doing it?
The assignment code above works with the PyTorch backend.

Thank you!

**Comment by suvadityamuk** [comment]
TensorFlow does not support dynamic tensor assignment in this manner, while PyTorch does. I do not think TensorFlow Backend would be able to support it in this way, although I think one of the maintainers should be a better person to comment.

**Comment by anas-rz** [comment]
Thank you for the letting know @innat  @suvadityamuk.

For my problem, this seems the only way out:

```
def forward_with_coords(coords_input, image_size):
        """Positionally encode points that are not normalized to [0,1]."""
        if keras.backend.backend() == "tensorflow":
            import tensorflow as tf
            coords = tf.Variable(coords_input)
            coords[:, :, 0].assign(coords[:, :, 0] / image_size[1])
            coords[:, :, 1].assign(coords[:, :, 1] / image_size[0])
            return coords
        elif keras.backend.backend() == 'torch':
            coords = coords_input.clone()
            coords[:, :, 0] = coords[:, :, 0] / image_size[1]
            coords[:, :, 1] = coords[:, :, 1] / image_size[0]
            return coords
        else:
            coords = coords_input.copy()
            coords.at[:, :, 0].set(coords[:, :, 0] / image_size[1])
            coords.at[:, :, 1].set(coords[:, :, 1] / image_size[0])
            return coords

```

If you have any better way, please let me know.

**Comment by cantonios** [comment]
> coords = coords_input.copy()
>             coords.at[:, :, 0].set(coords[:, :, 0] / image_size[1])
>             coords.at[:, :, 1].set(coords[:, :, 1] / image_size[0])
>             return coords

I believe this is incorrect for JAX.  The `.at[...].set(...)` method returns a _new_ tensor, so you would need to do
```
            coords = coords_input.at[:, :, 0].set(coords[:, :, 0] / image_size[1])
            coords = coords.at[:, :, 1].set(coords[:, :, 1] / image_size[0])
            return coords
```
JAX has the same issue as tensorflow, in that the tensors are immutable, so we can't just directly assign a slice via indexing.

**Comment by fchollet** [comment]
To do tensor assignment, you can use the following solutions:

1. Use the backend-native solution. Some backends support tensor assignment, so you could use what they offer -- but keep in mind that your code will then be specific to that backend.
2. Use Keras Core assignment ops. There are 2 assignment ops:
   1. [scatter_update](https://keras.io/keras_core/api/ops/core/#scatterupdate-function) for updates indexed by coordinates
   2. [slice_update](https://keras.io/keras_core/api/ops/core/#sliceupdate-function) for block-shaped updates

These ops will work with all backends.

For instance you can do:

```python
inputs = ops.zeros((5, 5))
start_indices = [3, 3]
updates = ops.ones((2, 2))
inputs = keras_core.ops.slice_update(inputs, start_indices, updates)
```

Which is equivalent to `inputs[3:, 3:] = updates`
