### ISSUE TITLE
`TFDataLayer` broken in 0.1.1 release

### ISSUE THREAD

**Issue by ianstenbit** [keras-team/keras-core#541]
After the 0.1.1 release, I am seeing the following error on CI for KerasCV:

```
...keras_core/src/layers/preprocessing/tf_data_layer.py", line 24
AttributeError: module 'keras_core.backend' has no attribute 'KerasTensor'
```

This same error does not exist for 0.1.0.

I'm not exactly clear on what the root cause is here, but it seems like potentially some sort of namex interaction? 
Going to pin KerasCV CI to 0.1.0 for now.

**Comment by fchollet** [comment]
This point for the need for extensive integration tests run against the public API rather than the internal API. We can't catch such issues with unit tests.

**Comment by fchollet** [comment]
Can you try at `main`?

**Comment by ianstenbit** [comment]
> Can you try at `main`?

After the latest [commit](https://github.com/keras-team/keras-core/commit/0bf7325b856548979557d01315b44bf1db67ad93) this is working correctly again.

Thank you!
