### ISSUE TITLE
Plans for an unified Tensor API

### ISSUE THREAD

**Issue by suvadityamuk** [keras-team/keras-core#543]
Hello!

I'm trying to understand, is there a possibility to create an unified Tensor API, something like `keras.Tensor`? I know that `KerasTensor` exists, but it is symbolic in nature and cannot be used to hold values. It could be a very simple native Keras construct that would basically just be an alias to the Tensor class of whichever backend is currently set.

Thoughts?

**Comment by fchollet** [comment]
Thanks for the suggestion. We've considered this, but we had to abandon the idea in order to preserve the ability to write custom components using backend-native APIs. This requires the tensors received by layers / etc to be backend-native tensors.
