### ISSUE TITLE
Behavior of ops.split

### ISSUE THREAD

**Issue by shivance** [keras-team/keras-core#544]
(This was originally found while working on [keras-nlp\#1110](https://github.com/keras-team/keras-nlp/pull/1110) )

An interesting revelation on the behavior of the split method across torch, tf and numpy

```
import torch
a = torch.ones(2, 8, 2, 0)
x = torch.split(a, 2, dim=-1)
print("splits = ", x)
```

output 
splits =  (tensor([], size=(2, 8, 2, 0)),)

```
import tensorflow as tf
b = tf.ones((2, 8, 2, 0))
y = tf.split(b, 2, axis=-1)
print("splits = ", y)
```

output 
splits =  [<tf.Tensor: shape=(2, 8, 2, 0), dtype=float32, numpy=array([], shape=(2, 8, 2, 0), dtype=float32)>, <tf.Tensor: shape=(2, 8, 2, 0), dtype=float32, numpy=array([], shape=(2, 8, 2, 0), dtype=float32)>]

```
import numpy as np

c = np.ones((2, 8, 2, 0))
z = np.split(c, 2, axis=-1)
print("splits = ", z)
```

output 
splits =  [array([], shape=(2, 8, 2, 0), dtype=float64), array([], shape=(2, 8, 2, 0), dtype=float64)]

How shall we handle this behavior to deliver same functionality !

**Comment by fchollet** [comment]
What about JAX?

It sounds like TF and numpy are consistent (apart from the fact that np uses float64, which is expected).

Our general approach is that we standardize on the numpy API. So here we should fix the torch op to make sure it follows the numpy behavior. Are you able to open a PR?

**Comment by AakashKumarNain** [comment]
IIRC JAX follows the same convention as numpy. So, apart from torch everything else seems consistent. But do we know the reasoning behind the divergence in torch? @shivance

**Comment by shivance** [comment]
Yes Jax has it's own numpy API which is consistent with numpy, regarding this behavior of Torch, I'll need to dig in. Currently pulled up in couple of PRs at KerasNLP end. Will followup in this thread or a PR by this weekend if that's okay ?

**Comment by fchollet** [comment]
Sounds great -- thank you!
