### ISSUE TITLE
Using torch backend

### ISSUE THREAD

**Issue by Giszy** [keras-team/keras-core#555]
Using PyTorch backend.
Epoch 1/3
32/32 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - mean_absolute_error: 0.4083 - loss: 0.2566
Epoch 2/3
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - mean_absolute_error: 0.3805 - loss: 0.2151
Epoch 3/3
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - mean_absolute_error: 0.3704 - loss: 0.2056
Epoch 1/5
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.2699 - mae: 0.4200
Epoch 2/5
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.2409 - mae: 0.3940
Epoch 3/5
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.2271 - mae: 0.3856
Epoch 4/5
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.2174 - mae: 0.3785
Epoch 5/5
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.2120 - mae: 0.3699
Epoch 1/3
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - mean_absolute_error: 0.7020 - loss: 0.3334
Epoch 2/3
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - mean_absolute_error: 0.4075 - loss: 0.1271
Epoch 3/3
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - mean_absolute_error: 0.3776 - loss: 0.1010
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - mean_absolute_error: 0.8608 - loss: 0.9672
Traceback (most recent call last):
  File "E:\custom_train_step_in_torch.py", line 483, in <module>
    gan.fit(dataloader, epochs=1)
  File "C:\Python_310\lib\site-packages\keras_core\src\utils\traceback_utils.py", line 123, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Python_310\lib\site-packages\keras_core\src\utils\module_utils.py", line 26, in initialize
    raise ImportError(
ImportError: This requires the tensorflow module. You can install it via `pip install tensorflow`

**Comment by Giszy** [comment]
Thanks. I've tried doing what you suggested, but the result is the same.
The original code is at https://github.com/keras-team/keras-io/blob/master/guides/keras_core/custom_train_step_in_torch.py.

**Comment by Giszy** [comment]
> Sounds like you're trying to use a feature that requires TF. Can you try to run `keras.config.disable_traceback_filtering()` and run again so we can see the full traceback?

Thanks. I've tried doing what you suggested, but the result is the same.
The original code is at https://github.com/keras-team/keras-io/blob/master/guides/keras_core/custom_train_step_in_torch.py.

**Comment by fchollet** [comment]
`keras.config.disable_traceback_filtering()` is not supposed to fix the problem it is supposed to give you a longer stack trace. You can run it and post the full stack trace here.
