### ISSUE TITLE
Implementation of `keras_core.ops.amax`

### ISSUE THREAD

**Issue by guillaumebaquiast** [keras-team/keras-core#561]
There might be two problems in the way `keras_core.ops.amax` is implemented:

* It [calls the class All](https://github.com/keras-team/keras-core/blob/main/keras_core/ops/numpy.py#L357) instead of [Amax](https://github.com/keras-team/keras-core/blob/main/keras_core/ops/numpy.py#L332)
* In numpy, `amax` is a just an alias for `max` (see [numpy doc](https://numpy.org/doc/stable/reference/generated/numpy.amax.html)). However, in keras_core, `max` [takes one more argument](https://github.com/keras-team/keras-core/blob/main/keras_core/ops/numpy.py#L2066C39-L2066C46) (`initial`) than `amax`. If the goal is to replicate numpy's structure, should they have the same arguments?

Proposal:
Make `keras_core.ops.amax` just call `keras_core.ops.max` (or the opposite), similarly to how [`keras_core.ops.abs` calls `keras_core.ops.absolute`](https://github.com/keras-team/keras-core/blob/main/keras_core/ops/numpy.py#L242)

**Comment by fchollet** [comment]
The first issue was a typo -- fixed now.

For the second issue, we're matching the JAX numpy API https://jax.readthedocs.io/en/latest/_autosummary/jax.numpy.amax.html

**Comment by guillaumebaquiast** [comment]
My second point was that `keras_core.ops.max` takes `initial` as argument, while `keras_core.ops.amax` doesn't. In JAX, both functions take `initial` as argument as well. Not sure if I'm missing something.

**Comment by fchollet** [comment]
Got it -- in this case it would make sense to add the argument in `amax`.
