### ISSUE TITLE
possible bug: code working with tensorflow/jax backends but not with pytorch

### ISSUE THREAD

**Issue by anas-rz** [keras-team/keras-core#566]
PR #565
While trying to convert the compact convolution transformer to backend agnostic, I am facing issue working with the PyTorch backend.
The model works with tensorflow/jax backends but throws an error with PyTorch.

Error for PyTorch backend:
`RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.`

**Comment by fchollet** [comment]
Thanks for the report. Can you run `keras.config.disable_traceback_filtering()` and then post the full stack trace?

**Comment by anas-rz** [comment]
Sure. Here it is:

```
RuntimeError                              Traceback (most recent call last)
[<ipython-input-3-2ff1d36f2d6b>](https://localhost:8080/#) in <cell line: 373>()
    371 cct_model = create_cct_model()
    372 cct_model.summary()
--> 373 history = run_experiment(cct_model)
    374 
    375 """

6 frames
[<ipython-input-3-2ff1d36f2d6b>](https://localhost:8080/#) in run_experiment(model)
    352     )
    353 
--> 354     history = model.fit(
    355         x=x_train,
    356         y=y_train,

[/usr/local/lib/python3.10/dist-packages/keras_core/src/utils/traceback_utils.py](https://localhost:8080/#) in error_handler(*args, **kwargs)
    112     def error_handler(*args, **kwargs):
    113         if not is_traceback_filtering_enabled():
--> 114             return fn(*args, **kwargs)
    115 
    116         filtered_tb = None

[/usr/local/lib/python3.10/dist-packages/keras_core/src/backend/torch/trainer.py](https://localhost:8080/#) in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_batch_size, validation_freq)
    291                 callbacks.on_train_batch_begin(step)
    292 
--> 293                 logs = self.train_function(data)
    294 
    295                 # Callbacks

[/usr/local/lib/python3.10/dist-packages/keras_core/src/backend/torch/trainer.py](https://localhost:8080/#) in one_step_on_data(data)
     96             """Runs a single training step on a batch of data."""
     97             data = data[0]
---> 98             return self.train_step(data)
     99 
    100         if self.jit_compile:

[/usr/local/lib/python3.10/dist-packages/keras_core/src/backend/torch/trainer.py](https://localhost:8080/#) in train_step(self, data)
     46             # Call torch.Tensor.backward() on the loss to compute gradients
     47             # for the weights.
---> 48             loss.backward()
     49 
     50             trainable_weights = self.trainable_weights[:]

[/usr/local/lib/python3.10/dist-packages/torch/_tensor.py](https://localhost:8080/#) in backward(self, gradient, retain_graph, create_graph, inputs)
    485                 inputs=inputs,
    486             )
--> 487         torch.autograd.backward(
    488             self, gradient, retain_graph, create_graph, inputs=inputs
    489         )

[/usr/local/lib/python3.10/dist-packages/torch/autograd/__init__.py](https://localhost:8080/#) in backward(tensors, grad_tensors, retain_graph, create_graph, grad_variables, inputs)
    198     # some Python versions print out the first line of a multi-line function
    199     # calls in the traceback and some print out the last line
--> 200     Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
    201         tensors, grad_tensors_, retain_graph, create_graph, inputs,
    202         allow_unreachable=True, accumulate_grad=True)  # Calls into the C++ engine to run the backward pass

RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.
```

**Comment by fchollet** [comment]
I strongly suspect the error message is completely misleading, and that the error has to do with the fact that non-differentiable data augmentation ops are included in the model. Can you try moving the data augmentation / preprocessing logic outside of the model?

**Comment by anas-rz** [comment]
Removed data augmentation layer altogether. Still throwing the same error.

**Comment by fchollet** [comment]
The problem is likely with the preprocessing part, `CCTTokenizer`. Try moving that out of the model?

**Comment by anas-rz** [comment]
You are right.
The problem was with positional embedding added by CCT Tokenizer.
Maybe this call to the layer was causing the error?
`dummy_outputs = self.call(dummy_inputs)`

`Trying to backward through the graph a second time..`

**Comment by anas-rz** [comment]
Should I stop gradient for this call?

**Comment by anas-rz** [comment]
Even tried moving it out of layer

```
if positional_emb:
        sequence_length, projection_dim = ops.shape(encoded_patches)[1], ops.shape(encoded_patches)[2]
        print(sequence_length, projection_dim)
        embed_layer = layers.Embedding(
            input_dim=sequence_length, output_dim=projection_dim
        )
        positions = ops.arange(start=0, stop=sequence_length, step=1)
        position_embeddings = embed_layer(positions)
        encoded_patches += position_embeddings
```

**Comment by fchollet** [comment]
> Should I stop gradient for this call?

This is a great idea, we should try that.

**Comment by anas-rz** [comment]
For the experiment, I replaced the embedding layer with a Dense layer and it worked. Attached is the code:

```
if positional_emb:
    sequence_length = ops.shape(encoded_patches)[1]
    positions = ops.arange(start=0, stop=sequence_length, step=1)
    projection_dim = ops.shape(encoded_patches)[-1]
    position_embeddings = layers.Dense(projection_dim)(encoded_patches)
    encoded_patches += position_embeddings
```

Seems the problem is with Embedding Layer.

**Comment by anas-rz** [comment]
Although the first version of example (which includes positional embedding) works with JAX the training time is very slow when compared with TensorFlow. Have not worked much with JAX but the discrepancy is big.

**Comment by anas-rz** [comment]
Performed all experiments on Google Colab.

**Comment by anas-rz** [comment]
I faced it again while working at #602

**Comment by anas-rz** [comment]
Sorry I accidently closed the issue

**Comment by fchollet** [comment]
Do you have a colab to reproduce the torch issue?

**Comment by fchollet** [comment]
> This is a great idea, we should try that.

I've applied this fix, let me know if it fixes your problem.

**Comment by anas-rz** [comment]
> Do you have a colab to reproduce the torch issue?

Sure [here it is](https://colab.research.google.com/drive/1fFSAxs_voybOJQAoK74EzX304h_g0KUd?usp=sharing)

**Comment by anas-rz** [comment]
> > This is a great idea, we should try that.

Sure. Let me try.
I also faced it in a layer calculating fft #602.

**Comment by anas-rz** [comment]
I cloned the latest repo and put its path to sys.path, uninstalled previous keras-core version and restarted runtime. It doesn't recognize the alias `MaxPool2D`. Changed it to MaxPooling and it requires building before fitting.

**Comment by anas-rz** [comment]
The previous version built the model and I was able to see it's summary too.

**Comment by fchollet** [comment]
> I cloned the latest repo and put its path to sys.path, uninstalled previous keras-core version and restarted runtime. It doesn't recognize the alias MaxPool2D. Changed it to MaxPooling and it requires building before fitting.

You shouldn't be using the codebase as if it were the `keras_core` package -- you must build it and install it first, which you can do from the codebase by running `python pip_build.py --install`.

**Comment by anas-rz** [comment]
>  which you can do from the codebase by running `python pip_build.py --install`.

I tried doing that but it didn't work tried: `pip install git+https://github.com/keras-team/keras-core.git` and it installed successfully. But the model still requires building .fit does not work.

**Comment by fchollet** [comment]
you should do `git clone https://github.com/keras-team/keras-core.git`, `python keras-core/pip_build.py --install`

**Comment by anas-rz** [comment]
It builds successfully. Throws the same error.

**Comment by guillaumebaquiast** [comment]
I think this has been solved by https://github.com/keras-team/keras-core/pull/663?
