### ISSUE TITLE
Question regarding the compatability of layers

### ISSUE THREAD

**Issue by Darryl-Shi** [keras-team/keras-core#570]
Hey,

Wondering if layers of a specifc backend (ie tensorflow) would be compatible in another backend?

ie,

Would tf.linalg used in a keras layer work with a pytorch backend? And would torch.tril work with a jax backend

Thank you

**Comment by fchollet** [comment]
No, it would not. In order for a layer to work across backend, it needs to be implemented using Keras APIs, e.g. `keras.ops.tril`. These ops work with any backend. A layer that uses any TF ops can only work with the TF backend.
