### ISSUE TITLE
Possible bug: Torch backend backpropagation 

### ISSUE THREAD

**Issue by soumik12345** [keras-team/keras-core#604]
I was attempting to replicate the [`demo_mnist_convnet` example](https://github.com/keras-team/keras-core/blob/main/examples/demo_mnist_convnet.py) by replacing `keras_core.layers` with `torch.nn.Module` inside a `keras_core.Model`. Although training with `model.fit` doesn't encounter any error, it seems that the model is not learning anything.

I further attempted to override the `train_step` function according to the guide [custom_train_step_in_torch](https://github.com/keras-team/keras-core/blob/main/guides/custom_train_step_in_torch.py), but that too did not fix the issue. I also tried to explicitly call `torch.nn.Module.zero_grad(self)` as recommended in the same guide, without any effect.

Colab to reproduce the issue [![](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/drive/1DwNOTbfkvZSyrQ5zzxd9zjQG-WavHcfE?usp=sharing)

**Comment by fchollet** [comment]
> replacing keras_core.layers with torch.nn.Module inside a keras_core.Model

This is not intended to be supported at this time. Only `Layer` objects are tracked by Keras, not torch Modules.

**Comment by soumik12345** [comment]
> This is not intended to be supported at this time. Only `Layer` objects are tracked by Keras, not torch Modules.

Is it possible to make new KerasCore layers abstracting torch Modules?

**Comment by fchollet** [comment]
It's possible, but you'd need to wrap the module in a layer in a way that makes it track the underlying `parameters()`. We haven't implemented anything like this yet. But it's likely simple.

**Comment by soumik12345** [comment]
> It's possible, but you'd need to wrap the module in a layer in a way that makes it track the underlying `parameters()`. We haven't implemented anything like this yet. But it's likely simple.

This would be a valuable feature, making `keras_core` compatible with likely the entirety of the PyTorch ecosystem.

**Comment by fchollet** [comment]
Would you like to explore implementing a prototype of a `TorchModuleWrapper`? If it's simple, we can auto-wrap any module upon assignment to a Keras Layer with the torch backend.

**Comment by fchollet** [comment]
It's probably going to be something like this (warning: entirely untested):

```python
class TorchModuleWarpper(Layer):
    def __init__(self, module, name=None):
        super().__init__(name=name)
        self.module = module

    def parameters(self, recurse=True):
        return self.module.parameters(recurse=recurse)

    def build(self, _):
        if not self.built:
            for param in self.module.parameters():
                variable = Variable(value=param, trainable=param.requires_grad)
                self._track_variable(variable)
        self.built = True

    def call(self, *args, **kwargs):
        return self.module.forward(*args, **kwargs)
```

**Comment by fchollet** [comment]
@soumik12345 I have it working with a couple of simple changes:

- The module wrapper can set `self.built = True` since torch module weights are already created (mind you, I guess this won't be the case with lazy modules, I have no idea how those work)
- There was a device placement issue, as is common with torch. I placed the module on GPU to make it work.

https://colab.research.google.com/drive/1gG93Fb03Ef-77suS6b7PqgWtMOopNyyF?usp=sharing

**Comment by soumik12345** [comment]
@fchollet 
Could you please make the notebook public? 😅

**Comment by soumik12345** [comment]
Also, should this be an officially supported feature on Keras Core? If not a feature, maybe this could be mentioned in a guide?

**Comment by fchollet** [comment]
> Also, should this be an officially supported feature on Keras Core? If not a feature, maybe this could be mentioned in a guide?

Sure, let's add it. First, please investigate the case where not all module parameters are created upon instantiation (lazy module). When that works, we can start a PR.

**Comment by soumik12345** [comment]
Hi @fchollet 
I figured out how to make lazy torch modules train with Keras by slightly modifying the proposed `TorchModuleWarpper`. Would love to know your thoughts.

Linked Notebook: https://colab.research.google.com/drive/124Vn_d7_WvE2UaieLaG-pQavQuB7xHV3?usp=sharing

**Comment by fchollet** [comment]
Thanks for the analysis! Is there a way to merge both classes into a single one?

Instead of doing an eager `_ = self.module(sample_input)`, we should leverage `backend.compute_output_spec` which will be more efficient.

**Comment by soumik12345** [comment]
> Thanks for the analysis! Is there a way to merge both classes into a single one?

Yes, let me attempt this.

**Comment by soumik12345** [comment]
> Is there a way to merge both classes into a single one?

Here's how the merged `TorchModuleWarpper` is looking
```python
class TorchModuleWarpper(keras.layers.Layer):
    def __init__(self, module, name=None):
        super().__init__(name=name)
        self.module = module.to("cuda")
        for param in self.module.parameters():
            variable = keras.backend.Variable(
                initializer=param, trainable=param.requires_grad
            )
            variable._value = param
            self._track_variable(variable)
        self.built = True

    def parameters(self, recurse=True):
        return self.module.parameters(recurse=recurse)

    def call(self, inputs, *args, **kwargs):
        return self.module.forward(inputs, *args, **kwargs)
```

Here's the updated notebook: https://colab.research.google.com/drive/1vy11aILVgrPtxKHAiohtKM6LlmpVj2EC?usp=sharing


> Instead of doing an eager `_ = self.module(sample_input)`, we should leverage `backend.compute_output_spec` which will be more efficient.

I couldn't find a function `backend.compute_output_spec`, do you mean that we should override `keras_core.layers.Layer.compute_output_spec`?

**Comment by fchollet** [comment]
> I couldn't find a function backend.compute_output_spec, do you mean that we should override keras_core.layers.Layer.compute_output_spec?

It would be `backend.compute_output_spec(self.__call__, *args, **kwargs)` where `*args, **kwargs` would be KerasTensors (and other arguments).

In fact you can just reuse `Layer._build_by_run_for_single_pos_arg()` and `Layer._build_by_run_for_kwargs` (which we probably need to expose via a single unified method).

**Comment by soumik12345** [comment]
Hi @fchollet 
Here's the `TorchModuleWarpper` modified as per your feedback (with some generous help from @ariG23498)
```python
class TorchModuleWarpper(keras.layers.Layer):
    def __init__(self, module, name=None):
        super().__init__(name=name)
        self.module = module.to("cuda")
        self.lazy = isinstance(self.module, nn.modules.lazy.LazyModuleMixin)
        if not self.lazy:
            self.track_module_parameters()

    def parameters(self, recurse=True):
        return self.module.parameters(recurse=not self.lazy)
    
    def track_module_parameters(self):
        for param in self.module.parameters():
            variable = keras.Variable(
                initializer=param, trainable=param.requires_grad
            )
            variable._value = param
            self._track_variable(variable)
        self.built = True
    
    def build(self, input_shape, *args, **kwargs):
        if not self.lazy:
            self._build_by_run_for_single_pos_arg(args)
            self._build_by_run_for_kwargs(kwargs)
        else:
            sample_input = torch.ones(*input_shape).to("cuda")
            _ = self.module(sample_input)
        self.track_module_parameters()

    def call(self, inputs, *args, **kwargs):
        if not self.built:
            self.build(inputs.shape[1:])
        return self.module.forward(inputs, *args, **kwargs)
```

Some observations wrt the following:

> Instead of doing an eager `_ = self.module(sample_input)`, we should leverage `backend.compute_output_spec` which will be more efficient.

It's probably not possible to build the parameters for lazy torch modules except by doing an eager `_ = self.module(sample_input)` since they don't initialize the parameters unless there's a forward pass. This is what the [official docs](https://pytorch.org/docs/stable/generated/torch.nn.modules.lazy.LazyModuleMixin.html) mention...

> Modules that lazily initialize parameters, or “lazy modules”, derive the shapes of their parameters from the first input(s) to their forward method. Until that first forward they contain `torch.nn.UninitializedParameter`s that should not be accessed or used, and afterward they contain regular `torch.nn.Parameter`s.

Would love to know your thoughts on this.

PS: Apologies for the delayed response.

**Comment by fchollet** [comment]
@soumik12345 thanks -- please open a PR and let's move the discussion to the PR. This should live in `backend/torch/torch_module_wrapper.py`. There is some light refactoring we will need.
