### ISSUE TITLE
Issue `ValueError: Expected metrics argument to be a list, tuple, or dict`

### ISSUE THREAD

**Issue by innat** [keras-team/keras-core#638]
In the following code, for the metric part, if set ` metrics=["accuracy"]` works but `metrics=keras.metrics.SparseCategoricalAccuracy(name='accuracy')` doesn't. 

```python
import os
os.environ["KERAS_BACKEND"] = "torch"

(x_train, y_train), (x_test, y_test) = keras.datasets.mnist.load_data()
x_train = x_train.reshape(60000, 784).astype("float32") / 255
x_test = x_test.reshape(10000, 784).astype("float32") / 255
inputs = keras.Input(shape=(784,))
dense = layers.Dense(64, activation="relu")
x = dense(inputs)
x = layers.Dense(64, activation="relu")(x)
outputs = layers.Dense(10)(x)
model = keras.Model(inputs=inputs, outputs=outputs, name="mnist_model")
model.compile(
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    optimizer=keras.optimizers.RMSprop(),
    # metrics=["accuracy"],
    metrics=keras.metrics.SparseCategoricalAccuracy(name='accuracy')
)
history = model.fit(
    x_train, y_train, batch_size=64, epochs=2, validation_split=0.2
)
```
> ValueError: Expected `metrics` argument to be a list, tuple, or dict. Received instead: metrics=<keras_core.src.metrics.accuracy_metrics.SparseCategoricalAccuracy object at 0x7a4d3b42bfa0> of type <class 'keras_core.src.metrics.accuracy_metrics.SparseCategoricalAccuracy'>

**Comment by fchollet** [comment]
You are passing a single `Metric` instance as the `metrics` argument. This was special-cased to work in tf.keras, but really, it's a syntax error. `metrics` is intended to be a list.

**Comment by innat** [comment]
@fchollet 
Thanks. But just to inform you, with `tf==2.12.0`, and keras=='2.12.0', passing **with/without** `[]`, both are valid (unless it was a bug). That makes sense because only one metric is used.

```python
# All are VALID in tf.keras 2.12
metrics=keras.metrics.SparseCategoricalAccuracy(name='accuracy')
metrics=[keras.metrics.SparseCategoricalAccuracy(name='accuracy')]
metrics='accuracy'
metrics=['accuracy']
```
