### ISSUE TITLE
Question: How can stacktrace filtering be disabled?

### ISSUE THREAD

**Issue by soumik12345** [keras-team/keras-core#642]
I am attempting to disable stacktrace filtering using the following code:
```python
!pip install -q git+https://github.com/keras-team/keras-core.git

import keras_core
keras_core.config.disable_traceback_filtering()
```
as per [this docstring](https://github.com/keras-team/keras-core/blob/945539b3a334606b05ef5623a6dc48bcbc151222/keras_core/utils/traceback_utils.py#L40-L57). However, I'm encountering the following error:
```
AttributeError: module 'keras_core' has no attribute 'config'
```

**Comment by fchollet** [comment]
You should *not* install the package via `pip install -q git+https://github.com/keras-team/keras-core.git`. Rather, you should do:

```
git clone https://github.com/keras-team/keras-core.git
cd keras-core
python3 pip_build.py --install
```

Then you will get access to the public API, including the `config` module. If you install the package from the source directly, you don't get the public API, you get the default directory structure based namespace.
