### ISSUE TITLE
GroupNormalization does not work with Pytorch

### ISSUE THREAD

**Issue by haroldle** [keras-team/keras-core#653]
For some reason, the GroupNormalization layer does not work with the Pytorch backend.

This is the link to a Google colab notebook that proves GroupNormalization failed in Pytorch backend: https://colab.research.google.com/drive/14-9KCl2wau-a1VRudZlJfpAOhW6RBYfz?usp=sharing

The links below prove GroupNormalization worked in Tensorflow and Jax backend:
https://colab.research.google.com/drive/1FAA20qoilEeLHJMThldb19ZiIO2F3Z75?usp=sharing => Jax backend
https://colab.research.google.com/drive/1cNZqT99fpEU97510OAh6QFRAFYSrEX1z?usp=sharing => Tensorflow backend

All of the notebooks have the same codes but a different backend.

**Comment by fchollet** [comment]
Thanks for the report. It seems to boil down to the fact that PyTorch doesn't respect standard conventions (used in NumPy/JAX/TF) for broadcasting with the `+` operator. We can fix it in the layer.

**Comment by fchollet** [comment]
This should now be fixed, please check. Fun fact: it sufficed to replace `*` with `multiply`. It seems PyTorch is internally inconsistent in how it handles broadcasting across these two ops.

**Comment by haroldle** [comment]
Yes. The problem is fixed. It seems quite weird to see inconsistencies in large code-based like Pytorch.
Thank you.
