### ISSUE TITLE
Please provide support for tf SavedModel format

### ISSUE THREAD

**Issue by sibyjackgrove** [keras-team/keras-core#664]
I was trying to integrate Keras Core into my existing model development pipeline. My pipeline uses the TF saved model format for inference since it is the easiest to load in another application without worrying about custom objects.

I am getting the following error when trying to save the trained model in tf saved model format: `model.save(model_folder,save_format="tf")` 

`ValueError: `'h5'` and `'t5'` formats are no longer supported via the `save_format` option. Please use the new `'keras'` format. Received: save_format=tf`

If I can't save in saved model format, it is difficult to use Keras Core in the existing pipeline. Could you suggest a workaround?

**Comment by fchollet** [comment]
You should be able to do `tf.saved_model.save(model, ...)` right now.

We are in fact adding limited support for SavedModel in Keras Core, which will be included in Keras 3.

**Comment by sibyjackgrove** [comment]
Thanks for the suggestion, @fchollet. I can save using `tf.saved_model.save`. But I can only use `tf.saved_model.load` to load the saved model.  Both `keras_core.models.load_model` and `tf.keras.models.load_model` doesn't work when loading models saved using `tf.saved_model.save`. So I cannot use `model.predict` or `model.evaluate`. Support for SavedModel in Keras Core would be highly appreciated.

**Comment by fchollet** [comment]
You should really be using a `.keras` file you intend to be able to reload the model as a Keras model. `SavedModel` is for inference-only export.
