### ISSUE TITLE
Error when Loading Merge Layer

### ISSUE THREAD

**Issue by StefanCaldararu** [keras-team/keras-core#673]
Hello All,

I am experiencing the following error when trying to load a model with a merge layer: ValueError: A `Concatenate` layer should be called on a list of at least 1 input. Received: input_shape=[[None, 2], [None, 2]]. 

I am using torch as my backend. When I run a similar configuration with standard Keras (rather than Keras_core), everything seems to work fine. Additionally, this error seems to appear when trying to load any merge layer (add, subtract, etc.). The models work perfectly fine when they have been constructed in the file, this error only seems to occur when trying to load in a model with a merge layer.

Thanks for the help!
p.s. sorry if this is a user issue, I am rather new to Keras.
[test_merge.py.zip](https://github.com/keras-team/keras-core/files/12284144/test_merge.py.zip)

**Comment by fchollet** [comment]
Thanks for the report. This appears to be an issue that has already been fixed. You can install Keras Core from GitHub to fix it, e.g.

```
git clone https://github.com/keras-team/keras-core.git
cd keras-core
python pip_build.py --install
```
