### ISSUE TITLE
Add `rsqrt` to keras_core.ops

### ISSUE THREAD

**Issue by shivance** [keras-team/keras-core#688]
Jax API : https://jax.readthedocs.io/en/latest/_autosummary/jax.lax.rsqrt.html
TF API : https://www.tensorflow.org/api_docs/python/tf/math/rsqrt
Torch API : https://pytorch.org/docs/stable/generated/torch.rsqrt.html

Numpy doesn't have it.

If we get this in, [this layer](https://github.com/keras-team/keras-nlp/blob/b04123b369413988c4d6dad1f25652bee29edcdf/keras_nlp/models/t5/t5_layer_norm.py#L36) in KerasNLP will become free of TF and we could use core ops.rsqrt directly !

I'm up for contributing this.

**Comment by fchollet** [comment]
Sure, you can put it in `math.py`.

**Comment by mattdangerw** [comment]
Why can't we just use the reciprocal of the `sqrt` directly in the "client" code of the ops layer? Don't fully understand why we need this, though not opposed.

**Comment by fchollet** [comment]
> directly in the "client" code of the ops layer?

Where exactly?

**Comment by shivance** [comment]
> Why can't we just use the reciprocal of the `sqrt` directly in the "client" code of the ops layer? Don't fully understand why we need this, though not opposed.

Forgive me for cross question here, why do Tf, Jax and PyTorch have seperate `rsqrt` method when they could compute it from inverse of `sqrt`?

**Comment by shivance** [comment]
> > directly in the "client" code of the ops layer?
> 
> Where exactly?

I think @mattdangerw is talking about this : 

https://github.com/keras-team/keras-nlp/blob/b04123b369413988c4d6dad1f25652bee29edcdf/keras_nlp/models/t5/t5_layer_norm.py#L36
