### ISSUE TITLE
Compatibility issue: 'ValueError: Graph disconnected' error with models using dict as inputs?

### ISSUE THREAD

**Issue by holongate** [keras-team/keras-core#690]
Hello,

It's really exiting to see Keras moving forward and offering us an opportunity to jump into JAX / Pytorch without a steep learning curve!
We understand the current project status, and what "high velocity" means of course, and we would like to contribute some feedback on a design pattern that does not seem covered by your examples.

We have since many years now normalized our TF/Keras model architecture patterns to use model creation functions that take dict for inputs and return dict for outputs.
In the attached minimal example python file, we have found that when the model creation function receives a dict, but uses the tensor after some operations, like intensity normalization, cast, ... instead of feeding it to a Layer,  the following error is raised at model creation:

```
ValueError: Graph disconnected: cannot find parent for tensor <KerasTensor shape=(None, 16), dtype=float32, name=keras_tensor_2> at operation '<Dense name=dense_1, built=True>'. The following previous operations were accessed without issue: []
```

This error is not raised for the current TF/Keras, and is present for all the backends, which should not be surprising given the early stage at which it is raised.

We have hundredths of code/models using this approach, and we would appreciate your feedback concerning its status (bug or definitely not supported).

Anyway, thanks a lot for your excellent work.

[minimal_example.py.txt](https://github.com/keras-team/keras-core/files/12314156/minimal_example.py.txt)

**Comment by fchollet** [comment]
Thanks for the report. Can you provide a reproducible code snippet to show the issue (i.e. a piece of code that can actually be run, in a standalone way)?

**Comment by holongate** [comment]
Hi François,

I attached a minimal example to my issue (please rename it as github does not allow .py files)

**Comment by fchollet** [comment]
> I attached a minimal example to my issue (please rename it as github does not allow .py files)

The code cannot be run since it is pseudocode. Please provide an executable code snippet.

**Comment by holongate** [comment]
Hi, really?
it is python code, just rename to .py. github don't want me to attach a .py file.

**Comment by holongate** [comment]
Thanks a lot.

**Comment by fchollet** [comment]
This should now be fixed at HEAD. Please check. You can pull the code from GitHub and run `python pip_build.py --install` to build and install the latest version of the package.
