### ISSUE TITLE
backend agnostic custom training loop

### ISSUE THREAD

**Issue by anas-rz** [keras-team/keras-core#691]
Is there a backend-agnostic way to write a training loop? In `keras` examples, there are many examples with custom `tf` training loops. Does Keras Core support any backend-agnostic way to write these loops?

**Comment by fchollet** [comment]
There is not -- the way training works in different is too different (in particular in JAX), so it's impossible to provide shared backend-agnostic abstractions for training. To write a custom training loop or a custom `train_step`, you must pick one specific backend.

It is still possible to write custom models that work with all backends, but that means they will need to implement 3 different `train_step` versions (one per backend).

**Comment by anas-rz** [comment]
Can we train a model using one `train_step` (like in TensorFlow)  and load it into another backend after saving (In Jax or TensorFlow)?
