### ISSUE TITLE
`predict_on_batch` does not work with multiple inputs

### ISSUE THREAD

**Issue by jbischof** [keras-team/keras-core#702]
I am trying to use the `predict_on_batch` method on a model with multiple inputs passed in a list. For all backends, `call` and `predict` work but `predict_on_batch` fails with the message:
```
ValueError: Layer 'text_encoder' expected 2 input(s). Received 1 instead.
```

The same code works without issue on `tf.keras`.

Here are some minimal colabs showing the difference:
* `tf.keras` colab [gist](https://colab.research.google.com/gist/jbischof/fae28580a224fe728bb02dfb8fd21301/tf-keras-and-predict_on_batch.ipynb)
* `keras_core` colab [gist](https://colab.research.google.com/gist/jbischof/0d4bf1fdfb1d9ca7583d13acc4eb261e/keras-core-and-predict_on_batch.ipynb)

**Comment by fchollet** [comment]
This is now fixed. Thanks for the report.
