### ISSUE TITLE
Add `mish` activation to keras_core.ops.nn

### ISSUE THREAD

**Issue by Frightera** [keras-team/keras-core#711]
TensorFlow and Pytorch have it implemented, JAX does not have it though. Is it still worth adding this activation function? Should be a one-liner in JAX too.

It has 1405 citations: [Mish: A self regularized non-monotonic activation function](https://scholar.google.com/citations?view_op=view_citation&hl=en&user=LwiJwNYAAAAJ&citation_for_view=LwiJwNYAAAAJ:q3oQSFYPqjQC)

**Comment by fchollet** [comment]
We already have it in `keras.activations` -- no clear need to have it in `ops.nn` IMO.
