### ISSUE TITLE
From KerasNLP to KerasCore : Add `RMSLayerNormalization`

### ISSUE THREAD

**Issue by shivance** [keras-team/keras-core#715]
Context: [kers-team/keras-nlp/#1207](https://github.com/keras-team/keras-nlp/issues/1207)

KerasNLP's T5 (now Llama too) uses a custom layer norm which is indeed RMSLayerNormalization. It's being used as it is from [here](https://github.com/keras-team/keras-nlp/blob/master/keras_nlp/models/t5/t5_layer_norm.py) to [here](https://github.com/shivance/keras-nlp/blob/llama-backbone/keras_nlp/models/llama/llama_layernorm.py) 
As it is getting popular, it would be good to officially support it as a Keras layer.

I can open a PR!

**Comment by shivance** [comment]
As @mattdangerw says [here](https://github.com/keras-team/keras-nlp/issues/1207#issuecomment-1676527644), we could either have a new layer `RMSLayerNormalization` or an option to the existing layer, something like LayerNormalization(rms_scaling=True).

**Comment by fchollet** [comment]
> something like LayerNormalization(rms_scaling=True).

I think that would be preferable. Thanks for the suggestion!

**Comment by mattdangerw** [comment]
Something like this?

```
Arguments

    Args:
        ...
        center: If True, add offset of `beta` to normalized tensor. If False,
            `beta` is ignored. Defaults to `True`.
        scale: If True, multiply by `gamma`. If False, `gamma` is not used.
            When the next layer is linear (also e.g. `nn.relu`), this can be
            disabled since the scaling will be done by the next layer.
            Defaults to `True`.
        rms_scaling: If True, `center` and `scale` are ignored, and the
            inputs are scaled by `gamma` and the inverse square root
            of the square of all inputs. This is an approximate and faster
            approach that avoids ever computing the mean of the input.
```

**Comment by fchollet** [comment]
Sure, sounds good to me. Thanks!
