### ISSUE TITLE
`swish` activation no longer exported at HEAD

### ISSUE THREAD

**Issue by jbischof** [keras-team/keras-core#716]
At HEAD, the `keras.activations.swish` symbol is no longer available. However, it works in the latest release.

```python
import keras_core as keras
# Works
keras.layers.Activation("swish")
# Throws
keras.activations.swish
>>> AttributeError: module 'keras_core.activations' has no attribute 'swish'
```

# Minimal colab repro
* HEAD [gist](https://colab.research.google.com/gist/jbischof/b0b115f7bd05c5fe31101d0fa59a2a66/swish-activation-export.ipynb)
* 0.4.1 [gist](https://colab.research.google.com/gist/jbischof/ca520702c5fc1f47498cdc77dae7ee5c/swish-activation-export-0-4-1.ipynb)

**Comment by jbischof** [comment]
Weirdly, I don't see any relevant changes to `activations.py` in the [history](https://github.com/keras-team/keras-core/commits/main/keras_core/activations/activations.py). Confused!

**Comment by fchollet** [comment]
I think you're looking at the private namespace instead of the public namespace. To install the package from GitHub, do the following:

```
git clone https://github.com/keras-team/keras-core.git
cd keras-core
python pip_build.py --install
```
