### ISSUE TITLE
Infinite validation loop in model.fit() when using Python generators

### ISSUE THREAD

**Issue by holongate** [keras-team/keras-core#720]
Hi,

We found that when using `model.fit()` with Python generators, the `validation_steps` does not seem to be used with infinite generators.
As a result,  the `fit()` function enters an infinite loop.

A gist is available here:
[minimal example](https://gist.github.com/holongate/142887f6c15c1a2724e8ad26f11bf2aa)

Checked against latest 0.1.4 keras-core.

**Comment by fchollet** [comment]
Thanks for the report -- this is now fixed at HEAD.
