### ISSUE TITLE
What is the correct way to install keras core on GPU?

### ISSUE THREAD

**Issue by emi-research-dl** [keras-team/keras-core#735]
Hi, I would like to know what is the correct way to install KerasCore on GPU. My doubt comes from the different versions of CUDA:

1. Tensorflow 2.13 requires cuda 11.8 and cudnn 8.6/8.8 2.
2. Torch requires cudnn 8.5

Both make conflicts. What would be the right way, could a specific version of cudatoolkit and cudnn be installed in an anaconda environment to avoid this?

**Comment by fchollet** [comment]
See instructions: https://keras.io/keras_core/#installation

In short, check out what is installed on colab-gpu and do the same. Today it is the following:

```
tensorflow: 2.12.0
jax: 0.4.14
torch: 2.0.1+cu118
```
