### ISSUE TITLE
How to convert keras core model to tflite correctly? 

### ISSUE THREAD

**Issue by batrlatom** [keras-team/keras-core#746]
Hi, I have quite a problem to use  keras_core together with tflite converter..

minimal reproducible example is here:

```
import os
import keras_core as keras


def get_model():
   # Create the base MobileNetV3Small model
   base_model = keras.applications.MobileNetV3Small(
    input_shape=(224, 224, 3),
    alpha=1.0,
    minimalistic=True,
    include_top=True,
    weights= None, #'imagenet',
    input_tensor=None,
    pooling=None,
    dropout_rate=0.2,
    classifier_activation='softmax',
    include_preprocessing=True
   )

   return base_model

model = get_model()

# option 1
try:
  converter = tf.lite.TFLiteConverter.from_keras_model(model)
  converter.optimizations = [tf.lite.Optimize.DEFAULT]
  # Set the input and output tensors to uint8 (APIs added in r2.3)
  converter.inference_input_type = tf.float32
  converter.inference_output_type = tf.float32
  tflite_model = converter.convert()
except:
  pass

# option 2
try:
  tf.saved_model.save(model, export_dir='test_model')
  converter = tf.lite.TFLiteConverter.from_saved_model('test_model')
  converter.optimizations = [tf.lite.Optimize.DEFAULT]
  # Set the input and output tensors to uint8 (APIs added in r2.3)
  converter.inference_input_type = tf.float32
  converter.inference_output_type = tf.float32
  tflite_model = converter.convert()
except:
  pass


```

the error I am getting is : 
2023-08-18 01:16:38.829399: I tensorflow/compiler/mlir/tensorflow/utils/dump_mlir_util.cc:255] disabling MLIR crash reproducer, set env var `MLIR_CRASH_REPRODUCER_DIRECTORY` to enable.
loc(fused["ReadVariableOp:", callsite("MobilenetV3small/Conv/BatchNorm/ReadVariableOp_1@__inference_serving_default_2170"("/opt/conda/lib/python3.8/site-packages/tensorflow/python/util/dispatch.py":1176:0) at callsite("/opt/conda/lib/python3.8/site-packages/tensorflow/python/util/traceback_utils.py":150:0 at callsite("/opt/conda/lib/python3.8/site-packages/keras_core/src/backend/tensorflow/core.py":47:0 at callsite("/opt/conda/lib/python3.8/site-packages/tensorflow/python/framework/tensor_conversion_registry.py":209:0 at callsite("/opt/conda/lib/python3.8/site-packages/tensorflow/python/framework/tensor_conversion.py":168:0 at callsite("/opt/conda/lib/python3.8/site-packages/tensorflow/python/framework/tensor_conversion.py":160:0 at callsite("/opt/conda/lib/python3.8/site-packages/tensorflow/python/util/dispatch.py":1176:0 at callsite("/opt/conda/lib/python3.8/site-packages/tensorflow/python/util/traceback_utils.py":150:0 at callsite("/opt/conda/lib/python3.8/site-packages/tensorflow/python/ops/numpy_ops/np_arrays.py":46:0 at "/opt/conda/lib/python3.8/site-packages/tensorflow/python/ops/numpy_ops/np_array_ops.py":165:0)))))))))]): error: missing attribute 'value'
LLVM ERROR: Failed to infer result type(s).
Aborted (core dumped)

I also tried other ways like use tf.saved_model.save() , but this gives me another error ...
2023-08-18 01:22:35.011598: I tensorflow/cc/saved_model/loader.cc:314] SavedModel load for tags { serve }; Status: success: OK. Took 285185 microseconds.
2023-08-18 01:22:35.077393: I tensorflow/compiler/mlir/tensorflow/utils/dump_mlir_util.cc:255] disabling MLIR crash reproducer, set env var `MLIR_CRASH_REPRODUCER_DIRECTORY` to enable.
loc(fused["ReadVariableOp:", "MobilenetV3small/Conv/BatchNorm/ReadVariableOp_1@__inference_serving_default_2170"]): error: missing attribute 'value'
LLVM ERROR: Failed to infer result type(s).
Aborted (core dumped)

**Comment by zehuiw** [comment]
@Ferev  Hi Milen I remember you were able to convert MobileNet to TFLite from  both TF/JAX backends. Have you run into any issues like this?

**Comment by Ferev** [comment]
Hi, let me know if the following works. The error you are getting seems to be TF-related. The code below uses a concrete function and sidesteps the SavedModel serialization.
```
import keras_core as keras
import tensorflow as tf

def get_model():
   # Create the base MobileNetV3Small model
   base_model = keras.applications.MobileNetV3Small(
    input_shape=(224, 224, 3),
    alpha=1.0,
    minimalistic=True,
    include_top=True,
    weights= None, #'imagenet',
    input_tensor=None,
    pooling=None,
    dropout_rate=0.2,
    classifier_activation='softmax',
    include_preprocessing=True
   )

   return base_model

model = get_model()


tf_callable = tf.function(
      model.call,
      autograph=False,
      input_signature=[tf.TensorSpec((1,224,224,3), tf.float32)],
)
tf_concrete_function = tf_callable.get_concrete_function()
converter = tf.lite.TFLiteConverter.from_concrete_functions(
      [tf_concrete_function], tf_callable
)
tflite_model = converter.convert()
```

**Comment by batrlatom** [comment]
@Ferev Hi, yes this works. It was super helpful, thank you! But I have one more problem, now related to the int8 quantization.
It looks like there are some differences between tf.keras and keras_core models, the code that worked for me lately, does
no work with tf.function . Can you help me with this one?



```
import keras_core as keras
import tensorflow as tf
import numpy as np

def get_model():
   # Create the base MobileNetV3Small model
   base_model = keras.applications.MobileNetV3Small(
    input_shape=(224, 224, 3),
    alpha=1.0,
    minimalistic=True,
    include_top=True,
    weights= None, #'imagenet',
    input_tensor=None,
    pooling=None,
    dropout_rate=0.2,
    classifier_activation='softmax',
    include_preprocessing=True
   )
   return base_model

model = get_model()
tf_callable = tf.function(
      model.call,
      autograph=False,
      input_signature=[tf.TensorSpec((1,224,224,3), tf.float32)],
)
tf_concrete_function = tf_callable.get_concrete_function()

converter = tf.lite.TFLiteConverter.from_concrete_functions(
      [tf_concrete_function], tf_callable
)

converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
converter.optimizations = [tf.lite.Optimize.DEFAULT]

# Set the input and output tensors to uint8 (APIs added in r2.3)
converter.inference_input_type = tf.uint8
converter.inference_output_type = tf.uint8

def representative_dataset_gen():
    for _ in range(100):
        data = np.random.rand(1, 224, 224, 3).astype(np.float32)
        #yield {'inputs0': data}
        yield [data]
        
converter.representative_dataset = representative_dataset_gen

tflite_quant_model = converter.convert()

with open('keras_mobilenetv3_uint8.tflite', 'wb') as f:
    f.write(tflite_quant_model)

```
The converter itself goes through, but when I want to make an inference, it makes an error regarding the quantization process. I think it could be related to the tf.function. Do you have any tips?

error message:



btw .. in the representative_dataset, I was using named inputs, but this tf.function probably stripped something of
```
ValueError: SignatureDef signature_key is None and model has 0 Signatures. None is only allowed when the model has 1 SignatureDef
```
```
def representative_dataset_gen():
    for _ in range(100):
        data = np.random.rand(1, 224, 224, 3).astype(np.float32)
        yield {'inputs0': data}
```
        

I am now using just this code and this could lead to the quantization problem

```
def representative_dataset_gen():
    for _ in range(100):
        data = np.random.rand(1, 224, 224, 3).astype(np.float32)
        yield [data]
```

**Comment by tarushbansal** [comment]
@batrlatom Just wondering whether you were able to find a workaround on the issue that you mentioned? Not only for quantisation, the signatures are also relevant for running inference on models with multiple inputs in order to not mix up input data.

**Comment by AhmedL99** [comment]
Any news on this topic?
