### ISSUE TITLE
Backend Doesn't Change to JAX

### ISSUE THREAD

**Issue by EngineerKhan** [keras-team/keras-core#749]
I have imported Keras Core as:

`import keras_core as k`

Even after explicitly setting the backend to JAX,

```
import os 
os.environ["KERAS_BACKEND"] = "jax"
```

It still shows tensorflow when I call:

`k.backend.backend()`

What's something I am missing/doing incorrectly here?

**Comment by fchollet** [comment]
You need to do this *before* you import `keras_core`.

**Comment by Jorgeberlin** [comment]
Thank you very much, worked for me perfectly!
