### ISSUE TITLE
is there a technical  impossibility for running it on Windows ?

### ISSUE THREAD

**Issue by stonebig** [keras-team/keras-core#761]
it's just the question, don't want to  slow down development.

**Comment by sampathweb** [comment]
Yes. That's the same for JAX as well and recommends users to use WSL2 when using Windows. https://pypi.org/project/jax/

**Comment by emi-research-dl** [comment]
Yeah @stonebig , I use my development environment with WSL2 and CUDA. I have the possible backends installed and haven't had any problems. In fact, TF recommends you to use WSL2. As a tip, be careful with the versions of CUDA and the backends you install, make sure they are compatible (see Colab).
