### ISSUE TITLE
Problem with `run_output_asserts` . Bug?

### ISSUE THREAD

**Issue by PatReis** [keras-team/keras-core#816]
In line 253 of keras_core.testing.test_case.py

If `assertTrue` output is a python `list` then I do not understand why output should have `.keys()` method,
unless of course output shoud inherit from `list` but implement a `.keys()` method. 
But I thought outputs of layers can be type pure list.
I am sorry for this stupid question but I can not resolve this assert.

```python
                # In line 253 of test_case.py
                elif isinstance(expected_output_shape, list):
                    self.assertTrue(isinstance(output, list))
                    self.assertEqual(
                        len(output.keys()),
                        len(
                            expected_output_shape.keys(),
                            msg="Unexpected number of outputs",
                        ),
                    )
```

**Comment by fchollet** [comment]
Yes, that's a bug. I just fixed it. It seems this part of the code is currently unused.
