### ISSUE TITLE
Add support for RaggedTensors to JAX and Pytorch Backend

### ISSUE THREAD

**Issue by IMvision12** [keras-team/keras-core#844]
Object detection models in KerasCV necessitate the use of ragged tensors. While TensorFlow as a backend supports this but jax and pytorch backend don't support it.

@ianstenbit @fchollet @tirthasheshpatel

**Comment by ianstenbit** [comment]
OD does not require ragged Tensors -- in many cases we pad to a dense representation.

JAX does not include support for ragged arrays, and I'm not aware of a strong Torch convention for this either, so for now ragged support is limited to the backend that offers them natively.
